### PR TITLE
Added bower.json file

### PR DESCRIPTION
**Pull request by brunowego**
Added support to bower, try: bower info rv-jquery-fontsize

### CODE REVIEW

**Comment by ramonvictor** [comment]
Thank you so much, @brunobatista! :)

**Comment by brunowego** [comment]
Hey you need make a new tag to implement the new features.

**Comment by ramonvictor** [comment]
@brunobatista, do you have new features to suggest?

**Comment by brunowego** [comment]
@ramonvictor the tag https://github.com/ramonvictor/rv-jquery-fontsize/tree/0.2.3 not have bower support. So please make a new tag with the bower file :D

try: bower info rv-jquery-fontsize

Of course need bower installed to do this.

Thanks!

**Comment by brunowego** [comment]
For now I try installed using: bower install rv-jquery-fontsize#master

Works but not tagged/fixed in one version.

**Comment by ramonvictor** [comment]
Sorry, @brunobatista, I haven't understood until you explain what you meant. Thank you so much. 
The new tag is now available: [0.2.4](https://github.com/ramonvictor/rv-jquery-fontsize/releases/tag/0.2.4).

**Pull request merged**
